# SPDX-FileCopyrightText: 2019 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 - 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed coturn settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please rename the variable (`{{ item.old }}` -> `{{ item.new }}`) on your configuration file (vars.yml).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "coturn_docker_network", "new": "coturn_container_network" }
    - { "old": "coturn_container_image_name_prefix", "new": "coturn_container_image_registry_prefix" }
    - "old": "coturn_container_stun_plain_host_bind_port"
      "new": "superseded by coturn_container_stun_plain_host_bind_port_tcp and coturn_container_stun_plain_host_bind_port_udp"
    - "old": "coturn_container_stun_tls_host_bind_port"
      "new": "superseded by coturn_container_stun_tls_host_bind_port_tcp and coturn_container_stun_tls_host_bind_port_udp"

- name: Fail if required coturn settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "item.when | bool and lookup('vars', item.name, default='') | string | length == 0"
  with_items:
    - { "name": "coturn_uid", when: true }
    - { "name": "coturn_gid", when: true }
    - { "name": "coturn_hostname", when: true }
    - { "name": "coturn_turn_static_auth_secret", when: "{{ coturn_authentication_method == 'auth-secret' }}" }
    - { "name": "coturn_lt_cred_mech_username", when: "{{ coturn_authentication_method == 'lt-cred-mech' }}" }
    - { "name": "coturn_lt_cred_mech_password", when: "{{ coturn_authentication_method == 'lt-cred-mech' }}" }
    - { "name": "coturn_turn_external_ip_address_auto_detection_echoip_service_url", when: "{{ coturn_turn_external_ip_address_auto_detection_enabled }}" }

- name: Fail if coturn_authentication_method is invalid
  ansible.builtin.fail:
    msg: >-
      coturn_authentication_method must be 'auth-secret' or 'lt-cred-mech'.
  when: "coturn_authentication_method not in ['auth-secret', 'lt-cred-mech']"
